### ISSUE TITLE
Shader file reading and compilation errors crash the whole application

### ISSUE THREAD

**Issue by rexim** [tsoding/boomer#53]
introduced in #52
