### ISSUE TITLE
filename for shader compilation error reporting are hardcoded

### ISSUE THREAD

**Issue by rexim** [tsoding/boomer#41]
introduced in #40
