### PR TITLE
Store shader path together with contents for convenient debugging.

### LINKED ISSUE #41: filename for shader compilation error reporting are hardcoded
introduced in #40

### PR DESCRIPTION
**Pull request by SolitudeSF**
closes #41 
Small wrapper around shader contents.

### CODE REVIEW

**Comment by SolitudeSF** [comment]
Actually, since #43, this gonna need some tweaks.

File: src/boomer.nim [hunk 1]
```diff
@@ -8,14 +8,24 @@ import x11/xlib, x11/x, x11/xutil, x11/keysym
 import opengl, opengl/glx
 import la
 
+type Shader = tuple[path, content: string]
+
+proc readShader(file: string): Shader =
+  result.path = file
+  result.content = block:
+    when nimvm:
```
Comment (rexim) [inline src/boomer.nim]: What does `nimvm` exactly indicate? Is it for the hot reloading thingy?

Comment (SolitudeSF) [reply src/boomer.nim]: it tells if this was executed on compile time (in nim's vm) or at runtime, to dispatch correct procedure. slurp reads file relative to the source file where its invoked. readFile read relative to current working directory.

Comment (SolitudeSF) [reply src/boomer.nim]: this is added complexity for minor gain. i could just prefix the shader path with "src/", since `nimble build` will always be executed from the same directory.

**Comment by rexim** [comment]
@SolitudeSF looks good to me. :+1: Thanks for the contribution!
